export default function handler(req, res) {
  const { id } = req.query;
  const cars = {
    'Verna-MPi-EX-2025': {
      model: 'Verna',
      images: ['/images/verna.jpeg'],
      engine_type: '1.5 l MPi Petrol',
      transmission: 'Automatic',
      fuel_efficiency: '18 km/l',
      dimensions: { length: '4.5 m', width: '1.7 m', height: '1.5 m' },
      carPricingHistory: [{ price: 14000 }],
      carFeatures: [{ feature_id: 94, name: 'Projector headlamps', value: 'Yes', category: 'Exterior - Lighting' }],
    },
    'Creta-SX-2024': {
      model: 'Creta',
      images: ['/images/creta.jpeg'],
      engine_type: '1.6 l Diesel',
      transmission: 'Manual',
      fuel_efficiency: '20 km/l',
      dimensions: { length: '4.3 m', width: '1.8 m', height: '1.6 m' },
      carPricingHistory: [{ price: 18000 }],
      carFeatures: [{ feature_id: 95, name: 'Sunroof', value: 'Yes', category: 'Exterior' }],
    },
    'i20-Sportz-2023': {
      model: 'i20',
      images: ['/images/i20.jpeg'],
      engine_type: '1.2 l Petrol',
      transmission: 'CVT',
      fuel_efficiency: '19 km/l',
      dimensions: { length: '4.0 m', width: '1.7 m', height: '1.5 m' },
      carPricingHistory: [{ price: 12000 }],
      carFeatures: [{ feature_id: 96, name: 'Touchscreen Infotainment', value: 'Yes', category: 'Interior' }],
    },
    'Venue-IMT-2022': {
      model: 'Venue',
      images: ['/images/venue.jpeg'],
      engine_type: '1.0 l Turbo Petrol',
      transmission: 'IMT',
      fuel_efficiency: '18 km/l',
      dimensions: { length: '4.1 m', width: '1.8 m', height: '1.6 m' },
      carPricingHistory: [{ price: 16000 }],
      carFeatures: [{ feature_id: 97, name: 'Wireless Charging', value: 'Yes', category: 'Interior' }],
    },
    'Tucson-AWD-2025': {
      model: 'Tucson',
      images: ['/images/tucson.jpeg'],
      engine_type: '2.0 l Diesel',
      transmission: 'Automatic',
      fuel_efficiency: '16 km/l',
      dimensions: { length: '4.6 m', width: '1.9 m', height: '1.7 m' },
      carPricingHistory: [{ price: 25000 }],
      carFeatures: [{ feature_id: 98, name: 'ADAS', value: 'Yes', category: 'Safety' }],
    },
    'Sonata-GLS-2024': {
      model: 'Sonata',
      images: ['/images/sonata.jpeg'],
      engine_type: '2.5 l Petrol',
      transmission: 'Automatic',
      fuel_efficiency: '15 km/l',
      dimensions: { length: '4.9 m', width: '1.9 m', height: '1.5 m' },
      carPricingHistory: [{ price: 22000 }],
      carFeatures: [{ feature_id: 99, name: 'Leather Seats', value: 'Yes', category: 'Interior' }],
    },
    'Elantra-SE-2023': {
      model: 'Elantra',
      images: ['/images/elantra.jpeg'],
      engine_type: '2.0 l Petrol',
      transmission: 'Automatic',
      fuel_efficiency: '17 km/l',
      dimensions: { length: '4.6 m', width: '1.8 m', height: '1.4 m' },
      carPricingHistory: [{ price: 20000 }],
      carFeatures: [{ feature_id: 100, name: 'Bose Audio System', value: 'Yes', category: 'Interior' }],
    },
    'Accent-LX-2022': {
      model: 'Accent',
      images: ['/images/accent.jpeg'],
      engine_type: '1.6 l Petrol',
      transmission: 'Manual',
      fuel_efficiency: '19 km/l',
      dimensions: { length: '4.4 m', width: '1.7 m', height: '1.5 m' },
      carPricingHistory: [{ price: 13000 }],
      carFeatures: [{ feature_id: 101, name: 'Rear Parking Camera', value: 'Yes', category: 'Safety' }],
    },
    'Palisade-SEL-2025': {
      model: 'Palisade',
      images: ['/images/palisade.jpeg'],
      engine_type: '3.8 l V6',
      transmission: 'Automatic',
      fuel_efficiency: '14 km/l',
      dimensions: { length: '5.0 m', width: '2.0 m', height: '1.8 m' },
      carPricingHistory: [{ price: 35000 }],
      carFeatures: [{ feature_id: 102, name: 'Ventilated Seats', value: 'Yes', category: 'Interior' }],
    },
    'Kona-Electric-2024': {
      model: 'Kona Electric',
      images: ['/images/konaelectric.jpeg'],
      engine_type: 'Electric',
      transmission: 'Automatic',
      fuel_efficiency: '452 km/charge',
      dimensions: { length: '4.2 m', width: '1.8 m', height: '1.6 m' },
      carPricingHistory: [{ price: 28000 }],
      carFeatures: [{ feature_id: 103, name: 'Fast Charging', value: 'Yes', category: 'Battery' }],
    }
  };

  const mockData = cars[id] || { error: 'Car not found' };
  res.status(200).json(mockData);
}